# Generated by Django 5.1.4 on 2025-01-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='bi-diagram-3', help_text='مثال: bi-diagram-3', max_length=100, verbose_name='کلاس آیکون'),
        ),
    ]
