# Generated by Django 5.1.4 on 2025-01-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teams/')),
                ('full_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
