# Generated by Django 5.1.4 on 2025-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(default='Team work', max_length=150),
        ),
    ]
