# Generated by Django 5.1.4 on 2025-01-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_team_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='bi-diagram-3', help_text='مثال: bi-diagram-3', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.CharField(max_length=250),
        ),
    ]
